version: "2"

services:
  # zookeeper:
  #   image: docker.io/bitnami/zookeeper:3.9
  #   expose:
  #     - "9093"
  #   ports:
  #     - "2181:2181"
  #   volumes:
  #     - "zookeeper_data:/bitnami"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka:
  #   image: docker.io/bitnami/kafka:3.4
  #   ports:
  #     - "9092:9092"
  #   expose:
  #     - "9092"
  #   volumes:
  #     - "kafka_data:/bitnami"
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #   depends_on:
  #     - zookeeper

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - service_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
networks:
  service_network:
# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local
# version: '2'
# services:
#   zookeeper:
#     image: wurstmeister/zookeeper:3.4.6
#     ports:
#       - "2181:2181"
#   kafka:
#     image: wurstmeister/kafka:2.12-2.2.1
#     ports:
#       - "9092:9092"
#     expose:
#       - "9093"
#     environment:
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
